Its a database of the salary and benefits paid to City employees since fiscal year 2013. This data is summarized and presented on the Employee Compensation report hosted at http://openbook.sfgov.org. The features of dataset are as given below - 

Year Type - Fiscal (July through June) or Calendar (January through December) 

Year - An accounting period of 12 months. The City and County of San Francisco operates on a fiscal year that begins on July 1 and ends on June 30 the following year. The Fiscal Year ending June 30, 2012 is represented as FY 2011-2012. 

Organization Group Code - Org Group is a group of Departments. For example, the Public Protection Org Group includes departments such as the Police, Fire, Adult Probation, District Attorney, and Sheriff. 

Organization Group - Org Group is a group of Departments. For example, the Public Protection Org Group includes departments such as the Police, Fire, Adult Probation, District Attorney, and Sheriff. 

Department Code- Departments are the primary organizational unit used by the City and County of San Francisco. Examples include Recreation and Parks, Public Works, and the Police Department. 

Department - Departments are the primary organizational unit used by the City and County of San Francisco. Examples include Recreation and Parks, Public Works, and the Police Department. 

Union Code-Unions represent employees in collective bargaining agreements. A job belongs to one union, although some jobs are unrepresented (usually temporarily). 

Union - Unions represent employees in collective bargaining agreements. A job belongs to one union, although some jobs are unrepresented (usually temporarily). 

Job Family Code - Job Family combines similar Jobs into meaningful groups.

 Job Family - Job Family combines similar Jobs into meaningful groups. 
 
 Job Code - Jobs are defined by the Human Resources classification unit. Examples include gardeners, police officers, and accountants. Job - Jobs are defined by the Human Resources classification unit. Examples include gardeners, police officers, and accountants.
 
  Employee Identifier - Each distinct number in the “Employee Identifier” column represents one employee. These identifying numbers are not meaningful but rather are randomly assigned for the purpose of building this dataset. The column does not appear on the Employee Compensation report hosted on openbook.sfgov.org, but that report does show one row for each employee. Employee ID has been included here to allow users to reconstruct the original report. Note that each employee’s identifier will change each time this dataset is updated, so comparisons by employee across multiple versions of the dataset are not possible. 
  
  Overtime - Amounts paid to City employees working in excess of 40 hours per week. 
  
  Other Salaries - Various irregular payments made to City employees including premium pay, incentive pay, or other one-time payments. 
  
  Retirement - City contributions to employee retirement plans. 
  
  Health/Dental - City-paid premiums to health and dental insurance plans covering City employees. To protect confidentiality as legally required, pro-rated citywide averages are presented in lieu of employee-specific health and dental benefits. 
  
  Other Benefits - Mandatory benefits paid on behalf of employees, such as Social Security (FICA and Medicare) contributions, unemployment insurance premiums, and minor discretionary benefits not included in the above categories. 
  
  Total Benefits - The sum of all benefits paid to City employees. Class- Class of Normal salaries paid to permanent or temporary City employees. Note: In the Class variable - 1 : Low range salary 2 : Mid range salary 3 : High range salary

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv("train.csv")
dff = pd.read_csv("test.csv")
df.sample(5)

,ID,Year Type,Year,Organization Group Code,Organization Group,Department Code,Department,Union Code,Union,Job Family Code,...,Job Code,Job,Employee Identifier,Overtime,Other Salaries,Retirement,Health/Dental,Other Benefits,Total Benefits,Class
148850,174610,Fiscal,2013,1,Public Protection,FIR,FIR Fire Department,798,"Firefighters - Miscellaneous, Local 798",H000,...,H003,EMT/Paramedic/Firefighter,18530,5793.49,16483.25,22715.27,12976.17,2303.72,37995.16,3
88099,193759,Fiscal,2016,4,Community Health,DPH,DPH Public Health,163,Physicians and Dentists - Spv Physician Specia...,2200,...,2233,Supervising Physician Spec,4823,0.00,0.00,45686.12,13176.00,12104.73,70966.85,3
25232,37893,Fiscal,2016,1,Public Protection,POL,POL Police,911,Police Officers' Association,Q000,...,Q052,Sergeant 3,3313,106232.51,20517.70,26402.01,13182.25,4658.93,44243.19,3
138479,192359,Fiscal,2014,1,Public Protection,CRT,CRT Superior Court,191,"Court Interpreters, Local 39521",SCRT,...,620C,Court Interpreter,36206,52.97,2500.00,15718.72,12516.72,6035.41,34270.85,2
80259,100377,Fiscal,2016,2,"Public Works, Transportation & Commerce",MTA,MTA Municipal Transprtn Agncy,253,"Transport Workers - Transit Operators, Local 2...",9100,...,9163,Transit Operator,6113,8458.72,1494.49,17198.25,14148.33,6199.00,37545.58,2

In [5]:
# df.drop(columns=['Year Type', 'Organization Group', 'Department', 'Union', 'Job Family', 'Job','ID','Year', 'Union Code', 'Employee Identifier', 'Department Code','Job Family Code','Job Code'], inplace=True)
# dff.drop(columns=['Year Type', 'Organization Group', 'Department', 'Union', 'Job Family', 'Job','ID','Year', 'Union Code', 'Employee Identifier', 'Department Code','Job Family Code','Job Code'], inplace=True)
# df.sample(10).T

In [6]:
corr = df.corr()
corr.style.background_gradient(cmap='coolwarm')

In [8]:
x_train = df.drop(columns=['Class'])
y_train = df['Class']
x_test = dff

In [9]:
from sklearn import preprocessing
def convert(data):
    number = preprocessing.LabelEncoder()
    df['Organization Group Code'] = number.fit_transform(df['Organization Group Code'])
    df['Overtime'] = number.fit_transform(df['Overtime'])
    df['Other Salaries'] = number.fit_transform(df['Other Salaries'])
    df['Retirement'] = number.fit_transform(df['Retirement'])
    df['Health/Dental'] = number.fit_transform(df['Health/Dental'])
    df['Other Benefits'] = number.fit_transform(df['Other Benefits'])
    df['Total Benefits'] = number.fit_transform(df['Total Benefits'])
    # df['Other Benefits'] = number.fit_transform(df['Other Benefits'])
    # data['Source'] = number.fit_transform(data.Source)
    data=data.fillna(0)
    return data

x_train=convert(x_train)
x_test=convert(x_test)

In [10]:
# x_train= np.asarray(x_train)

x_train= np.asarray(x_train).astype(np.float32)
from tensorflow.keras.utils import to_categorical 

y_train1 = to_categorical(y_train, 4)
y_train1=np.asarray(y_train1)
type(x_train)

numpy.ndarray

In [12]:
import tensorflow as tf
from tensorflow.keras.layers import  Dense, Dropout
from tensorflow.keras.models import Sequential
tf.keras.backend.clear_session()
model = Sequential()
# Apply Dropout with 0.2 probability
# Add Fully Connected Layer with 128 units and activation function as 'relu'
model.add(Dense(1500, activation='relu'))
model.add(Dense(100, activation='relu'))
model.add(Dense(35, activation='relu'))
#Add Fully Connected Layer with 10 units and activation function as 'softmax'
model.add(Dropout(rate=0.2))
model.add(Dense(1, activation='softmax'))
# Compile the model
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')
# Use earlystopping
# from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping
# callback = tensorflow.keras.callbacks.EarlyStopping(monitor='val_accuracy', patience=2, min_delta=0.01)
# Fit the model
model.fit(x=x_train, y=y_train, batch_size=32, epochs=10) #,  callbacks=[callback])
# let`s train for few more epochs to improve the accuracy
# model.evaluate(X_test, y_test)
# CNN_train_acc = model.evaluate(x_train, y_train)[1]
# CNN_test_acc = model.evaluate(x_test, y_test)[1]
# CNN_loss = model1.evaluate(x_test, y_test)[0]
# final_df.loc[len(final_df.index)] = ['CNN' , CNN_train_acc, CNN_test_acc, CNN_loss]
# final_df

Epoch 1/10
4659/4659 [==============================] - 16s 3ms/step - loss: 0.0000e+00 - accuracy: 0.3265
Epoch 2/10
4659/4659 [==============================] - 20s 4ms/step - loss: 0.0000e+00 - accuracy: 0.3265
Epoch 3/10
4659/4659 [==============================] - 18s 4ms/step - loss: 0.0000e+00 - accuracy: 0.3265
Epoch 4/10
4659/4659 [==============================] - 16s 4ms/step - loss: 0.0000e+00 - accuracy: 0.3265
Epoch 5/10
4659/4659 [==============================] - 16s 3ms/step - loss: 0.0000e+00 - accuracy: 0.3265
Epoch 6/10
4659/4659 [==============================] - 16s 3ms/step - loss: 0.0000e+00 - accuracy: 0.3265
Epoch 7/10
4659/4659 [==============================] - 17s 4ms/step - loss: 0.0000e+00 - accuracy: 0.3265
Epoch 8/10
4659/4659 [==============================] - 18s 4ms/step - loss: 0.0000e+00 - accuracy: 0.3265
Epoch 9/10
4659/4659 [==============================] - 12s 3ms/step - loss: 0.0000e+00 - accuracy: 0.3265
Epoch 10/10
4659/4659 [==============================] - 18s 4ms/step - loss: 0.0000e+00 - accuracy: 0.3265

In [ ]:
import pyttsx3
text = pyttsx3.init()
s = 'The code is Compiled in one'
text.say(s)
text.runAndWait()

In [ ]:
# model.fit(x_train, y_train, batch_size = 32, epochs= 20, initial_epoch=5)
model.evaluate(x_train, y_train)
Y_PRED = model.predict(x_test)

In [ ]:
test = pd.read_csv("test.csv")

In [ ]:
submit = test['ID']

In [ ]:
submit.append(pd.Series(Y_PRED))
submit.sample(6)

In [ ]:
submit.to_csv('sub1.csv')

In [ ]:
ddf = pd.read_csv('test.csv')

In [ ]:
ddf.sample(10)